
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Plugin.Bright.Serialization;
using System.Collections.Generic;
using System;

namespace cfg.test
{
   
public sealed partial class TbTestTag
{
    private readonly Dictionary<int, test.TestTag> _dataMap;
    private readonly List<test.TestTag> _dataList;
    
    public TbTestTag(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, test.TestTag>();
        _dataList = new List<test.TestTag>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            test.TestTag _v;
            _v = test.TestTag.DeserializeTestTag(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public Dictionary<int, test.TestTag> DataMap => _dataMap;
    public List<test.TestTag> DataList => _dataList;

    public test.TestTag GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public test.TestTag Get(int key) => _dataMap[key];
    public test.TestTag this[int key] => _dataMap[key];

    public void ForeachCfg(Func<test.TestTag, bool> callback)
    {
        foreach(var v in _dataList)
        {
            if(!callback(v))
            {
                break;
            }
        }
    }

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        OnResolveFinish(_tables);
    }


    partial void OnResolveFinish(Dictionary<string, object> _tables);
}

}
