# This is a basic workflow to help you get started with Actions

name: sync-gitee-mirror

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Gitee Pages Action
        # You may pin to the exact commit or the version.
        # uses: yanglbme/gitee-pages-action@3bb86e685ca25d05177e4ec96c032acf4a5dd9ff
        uses: yanglbme/gitee-pages-action@v1.2.8
        with:
          # The Gitee username, like yanglbme
          gitee-username: wang-qinghui
          # The Gitee password
          gitee-password: wangqinghui2333
          # The Gitee repository, like doocs/leetcode
          gitee-repo: wang-qinghui/AshFramework
          # Which branch to build
          #branch: # optional, default is master
          # Which directory to build
         # directory: # optional, default is 
          # Use force https or not
          #https: # optional, default is true
